### ISSUE TITLE
Keep the old pedestal-swagger

### ISSUE THREAD

**Issue by rachbowyer** [frankiesardo/route-swagger#24]
Hi,

Appreciate that you have decided to move forward with a new project route-swagger. Would it be possible to keep the old pedestal-swagger project available binary+source? We have production pedestal-swagger dependencies and this way it will be easier for us to remain on pedestal-swagger until we are ready to migrate. 

Thanks
Rachel

**Comment by frankiesardo** [comment]
Hi @rachbowyer . I appreciate you were using the old pedestal-swagger, but the source has not been lost. You can get it from source control at https://github.com/frankiesardo/route-swagger/tree/97c69ca6ed3e684180db0feec9582991997a5a4d. All the binaries available in clojars will remain there so there's no reason to worry :)

As a migration path https://github.com/oliyh/pedestal-api should provide the most similar api experience to the old pedestal-swagger
