### ISSUE TITLE
How to configure the UI?

### ISSUE THREAD

**Issue by bfontaine** [frankiesardo/route-swagger#25]
Hello,

Is there a way to configure the Swagger UI? I can’t find it. I’d like to set `validatorUrl: null` as shown on this issue: https://github.com/swagger-api/swagger-ui/issues/630. Thanks!

**Comment by frankiesardo** [comment]
Hi @bfontaine. I'm using [metosin/ring-swagger-ui](https://github.com/metosin/ring-swagger-ui) project internally so you might want to poke in there to see if there is any configuration.

As a quick and dirty fix you can roll your own `swagger-ui` interceptor and change the `index.html` served [here](https://github.com/frankiesardo/route-swagger/blob/master/src/route_swagger/interceptor.clj#L38)

Hope it helps

**Comment by bfontaine** [comment]
Thanks, I’ll look into that :smiley:
